apiVersion: batch/v1
kind: Job
metadata:
  name: canneal
  labels:
    name: canneal
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_canneal
        name: canneal
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c <cores> ./run -a run -S parsec -p canneal -i native -n <n>"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "<node_label>"
