apiVersion: batch/v1
kind: Job
metadata:
  name: ferret
  labels:
    name: ferret
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_ferret
        name: ferret
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0,1 ./run -a run -S parsec -p ferret -i native -n 2"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-2core"
