apiVersion: v1
kind: Pod
metadata:
  name: some-memcached
  labels:
    name: some-memcached
spec:
  containers:
    - image: anakli/memcached:t1
      name: memcached
      imagePullPolicy: Always
      command: ["/bin/sh"]
      args: ["-c", "taskset -c 0,1,2,3 ./memcached -t 4 -u memcache"]
  nodeSelector:
    cca-project-nodetype: node-c-4core


