apiVersion: batch/v1
kind: Job
metadata:
  name: dedup
  labels:
    name: dedup
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_dedup
        name: dedup
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c <cores> ./run -a run -S parsec -p dedup -i native -n <n>"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "<node_label>"
